# Full Example: https://github.com/samholt/L2MAC/blob/master/config/config.yaml
# Reflected Code: https://github.com/samholt/L2MAC/blob/master/l2mac/config.py
llm:
  api_type: "openai"  # or azure etc. Check ApiType for more options
  model: "gpt-4-turbo-preview"  # or "gpt-4-turbo"
  base_url: "https://api.openai.com/v1"  # or forward url / other llm url
  api_key: "YOUR_API_KEY"